modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="mekaweapons"
version="${mod_version}"
displayName="Mekanism: Weapons"
authors="oMeranha"
description='''Weapons for Mekanism.'''
[[dependencies.mekaweapons]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekaweapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekaweapons]]
    modId="mekanism"
    mandatory=true
    versionRange="10.4.0.14"
    ordering="AFTER"
    side="BOTH"
